### ISSUE TITLE
Border Check

### ISSUE THREAD

**Issue by CHeuberger** [CHeuberger/JZirconium#9]
Test if fences and forts are legal.
* `[]{}` must not have the same zone outside horizontally
* `[]{}` must have the zone or border inside horizontally
* `=~` must have zone or border on only one side vertically (?)

**Comment by Strohtaler** [comment]
this will hinder zones inside another zone like in
```
 ======= 
[       ]
[  ~~~  ]
[  { }  ]
[  ~~~  ]
[       ]
 ======= 
```
